<?php
define("ROUND_NUM", "UP");
define("YEAR_DAY", "360");
define("USD_KHR", "4100");
define("NBC_EXCHANGE_URL", "https://www.nbc.org.kh/english/economic_research/exchange_rate.php");
define("COMPANY_NAME", "BE SYSTEM");
define("COMPANY_NAME_KH", "");
define("EN_BTB_ADDRESS", "Street 221, A");
define("EN_HO_ADDRESS", "#09 A1 A2");
define("EN_HO_TEL", "Tel : 069 455555/ 099 788883");
define("KH_BTB_ADDRESS", "អគារលេខ B2-109, B2-110,សង្កាត់​ទន្លេបាសាក់ ខណ្ឌចំការមន រាជធានីភ្នំពេញ");
define("TEST", "Testing123");
define("TESTING", "");
define("CONTRACT_PRE", "LHL");
define("PROV_RATE_TO_SUB_STD", "0.1");
define("PROV_RATE_TO_DOUBTFUL", "0.2");
define("PROV_RATE_TO_LOSS_LOAN", "0.7");
define("IDLE_TIMEOUT", "30");
define("IDLE_ALERT", "20");
define("ROUND", "2");
define("ROUND_DIGIT", "0");
define("CLOSE_LC_STATUS", "7");
define("GENERAL_LC_STATUS", "2");
define("REVERT_CLASS_STD", "0");
define("CLASS_NEW_PRAKAS", "0");
define("HOLIDAY_SH_DIRECTION", "FWD");
define("REPAY_CAL", "");
define("AIR_SCH_FLG", "0");
define("CLOSE_L_STATUS", "6");
define("MFI_START_DATE", "2016-08-31");
define("WO_CREDIT_COA_NAME", "Recovery on Loans Previously Charged-Off");
define("SYS_INT_RATE_FREQ", "M");
